---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "humhub.fullname" . }}
  labels:
    {{- include "humhub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "humhub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "humhub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- if .Values.podSecurityContext }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{ else }}
        {{- toYaml .Values.defaults.podSecurityContext | nindent 8 }}
        {{- end }}
      initContainers:
      {{ if .Values.chownInitContainer.enabled }}
          - name: set-volume-permissions
            image: {{ .Values.chownInitContainer.image }}
            command: ['sh', '-c', 'chown 100:101 {{ range $name, $path := .Values.defaults.mounts }}/mnt/{{ $path }} {{ end }}']
            securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
            volumeMounts:
                {{- range $name, $path := .Values.defaults.mounts }}
                {{- if $path }}
                - mountPath: /mnt/{{ $path }}
                  name: data
                  subPath: {{ $path }}
                {{- end }}
                {{- end }}
      {{ end }}
      volumes:
          - name: data
            persistentVolumeClaim:
                claimName: {{ include "humhub.pvcName" . }}
                readOnly: false
      containers:
        - name: humhub
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
              - name: TZ
                value: {{ .Values.tz }}

              # HTTP
              - name: HUMHUB_PROTO
                value: {{ .Values.proto }}
              - name: HUMHUB_HOST
                value: "{{ .Values.host }}"

              # NGINX
              - name: NGINX_CLIENT_MAX_BODY_SIZE
                value: {{ .Values.nginx.clientMaxBodySize | quote }}
              - name: NGINX_KEEPALIVE_TIMEOUT
                value: {{ .Values.nginx.keepaliveTimeout | quote }}

              # PHP
              - name: PHP_POST_MAX_SIZE
                value: {{ .Values.php.postMaxSize | quote }}
              - name: PHP_UPLOAD_MAX_FILESIZE
                value: {{ .Values.php.uploadMaxFilesize | quote }}
              - name: PHP_MAX_EXECUTION_TIME
                value: {{ .Values.php.maxExecutionTime | quote }}
              - name: PHP_MEMORY_LIMIT
                value: {{ .Values.php.memoryLimit | quote }}

              # Database
              - name: HUMHUB_DB_HOST
                value: {{ .Values.db.host | quote }}
              - name: HUMHUB_DB_USER
                value: {{ .Values.db.user | quote }}
              - name: HUMHUB_DB_PORT
                value: {{ .Values.db.port | quote }}
              - name: HUMHUB_DB_NAME
                value: {{ .Values.db.name | quote }}
              - name: HUMHUB_DB_PASSWORD
                valueFrom:
                    secretKeyRef:
                        key: {{ .Values.db.password.secretKey }}
                        name: {{ .Values.db.password.secretName }}

              # Custom environment variables
              {{ range $env := .Values.env }}
              - {{ toJson $env }}
              {{ end }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
              {{- range $name, $path := .Values.defaults.mounts }}
              {{- if $path }}
                - mountPath: /var/www/localhost/htdocs/{{ $path }}
                  name: data
                  subPath: {{ $path }}
              {{- end }}
              {{- end }}
          startupProbe:
              {{ toYaml .Values.health.startupProbe | nindent 14 }}
              httpGet:
                  path: /
                  port: http
          livenessProbe:
              {{ toYaml .Values.health.livenessProbe | nindent 14 }}
              httpGet:
                  path: /
                  port: http
          readinessProbe:
              {{ toYaml .Values.health.readinessProbe | nindent 14 }}
              httpGet:
                  path: /
                  port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
