replicaCount: 1

image:
  repository: ghcr.io/mriedmann/humhub-allinone
  pullPolicy: IfNotPresent
  tag: ""

# -- Use PRIVILEGED init container to correct permissions of your volumes (NOTICE: it does not fix them recursively)
chownInitContainer:
    enabled: true
    image: busybox:1.36.0-musl

health:
    startupProbe:
        # defaults to 300s (5m) - give the migration script a time
        periodSeconds: 5
        failureThreshold: 60
    livenessProbe:
        periodSeconds: 55
        failureThreshold: 1
    readinessProbe:
        periodSeconds: 30
        failureThreshold: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}

securityContext:
    capabilities:
        drop: ["ALL"]
    runAsNonRoot: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#      - path: /
#        backend:
#          serviceName: chart-example.local
#          servicePort: 80
#  tls: []
#    - secretName: chart-example-tls
#      hosts:
#        - chart-example.local

# -- Pod resources
resources: {}

# -- Autoscaling: Officially not supported, but available. Use at own risk!
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Stick Pods to a node
nodeSelector: {}

# -- Allow execution on given node pools
tolerations: []

# -- Groups pods by nodes. Keep them together or separated
affinity: {}

# -- Persistence
pvc:
    # -- Should the Helm Chart create PersistentVolumeClaim object?
    create: true

    # -- PVC name
    name: humhub-pv

    # -- PVC size (valid only if .pvc.create = true)
    size: 10Gi

    # -- PV class name (valid only if .pvc.create = true)
    #className: local-path

    # -- Existing PV name (valid only if .pvc.create = true)
    volumeName: "humhub"


defaults:
    podSecurityContext:
        fsGroup: 101
        fsGroupChangePolicy: Always
    # -- Syntax: mount name: directory in the root application directory. Overwrite with empty value to skip mounting
    mounts:
        uploads: uploads
        assets: assets
        modules: protected/modules
        themes: themes
