name: Test and release
on:
    push:
    workflow_dispatch:
        inputs: {}

jobs:
    helm:
        uses: riotkit-org/.github/.github/workflows/release.helm.yaml@release-1
        with:
            chartPath: charts/humhub
            chartRepoName: "riotkit-org/charts/"
            chartName: humhub
